### ISSUE TITLE
슬랙 구독기능 구현에 대한 리서치

### ISSUE THREAD

**Issue by giyeonkwon** [laranhee/devwithluv.dev#39]
### Todos
- [ ] 슬랙 구독기능에 문서 읽기
- [ ] 슬랙 구독기능 구현에 대한 방법 문서화하기
- [ ] 스텝 및 태스크 나누기
